name: bluebuild
on:
  push:
    paths:
      - "00-minimal/**"
      - "10-two-images/**"
      - ".github/workflows/build-simple.yml"
    branches:
      - main

  pull_request:
  workflow_dispatch: # allow manually triggering builds
jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        recipe:
          # 00-minimal
          - folder: ./00-minimal
            file: recipe.yml

          # 10-two-images
          - folder: ./10-two-images
            file: recipe-gnome.yml
          - folder: ./10-two-images
            file: recipe-kde.yml

    steps:
      # the build is fully handled by the reusable github action
      - name: Build Custom Image
        uses: blue-build/github-action@v1.6
        with:
          recipe: ${{ matrix.recipe.file }}
          working_directory: ${{ matrix.recipe.folder }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
